language: python
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=flake8

install: pip install -U tox

script: tox -- --verbose -p no:sugar
